# Javascript

## 비동기를 다루는 또 다른 방법 ( async - await )

> async function 함수이름() {} <br/>
const 함수이름 = async () => {}

#### *Example 1.*

```js

// Promise 객체를 리턴하는 함수

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
            resolve(ms);
        }, ms)
    })
}

// Promise 객체를 이용해서 비동기 로직을 수행할 때

p(1000).then(ms => {
    console.log(`${ms} ms 후에 실행된다.`);
});

// Promise 객체를 리턴하는 함수를 await로 호출하는 방법

const ms = await p(1000);
console.log(`${ms} ms 후에 실행된다.`);
// error가 나올 것이며 await쓰려는 것이 유효하려면 async로 감싸져 있어야한다.

```

#### *Example 2.*

```js

// await 를 사용하는 경우, 항상 async 함수 안에서 사용되어야 한다.

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
            resolve(ms);
        }, ms)
    })
}

async function main(){
    const ms = await p(1000);
    console.log(`${ms} ms 후에 실행된다.`);
})();

// Promise 객체가 rejected 된 경우의 처리를 위해 try catch를 이용한다.

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
           // resolve(ms);
           reject(new Error('reason'));
        }, ms);
    });
}

(async function main() {
    try {
        const ms = await p(1000);
        //
    } catch (error) {
        console.log(error);
    }
})();

// async function 에서 return 되는 값은 Promise.resolve 함수로 감싸서 리턴된다.

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
           // resolve(ms);
           reject(new Error('reason'));
        }, ms);
    });
}

async function asyncP() {
    return 'Mark';
}

async function main() {
    try {
        const name = await asyncP();
        console.log(name);
    } catch (error) {
        console.log(error);
    }
})();
// Mark라고 출력이된다.

// ms을 넣어 몇 초 뒤 나오게 하는 것

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
           resolve(ms);
           // reject(new Error('reason'));
        }, ms);
    });
}

async function asyncP() {
    const ms = await p(1000);
    return 'Mark: ' + ms;
}

async function main() {
    try {
        const name = await asyncP();
        console.log(name);
    } catch (error) {
        console.log(error);
    }
})();

// Mark : 1000 이라고 출력이 된다.

function p(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(() => {
           // resolve(ms);
           reject(new Error('reason'));
        }, ms);
    });
}

async function asyncP() {
    const ms = await p(1000);
    return 'Mark: ' + ms;
}

async function main() {
    try {
        const name = await asyncP();
        console.log(name);
    } catch (error) {
        console.log(error);
    }
})();

```

#### *Example 3.*

```js

function p(ms) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(ms);
        }, ms);
    });
}

// Promise

p(1000)
  .then(() => p(1000))
  .then(() => p(1000))
  .then(() => {
      console.log('3000 ms 후에 실행');
  });

// async await

async function main() {
    await p(1000);
    await p(1000);
    await p(1000);
    console.log('3000 ms 후에 실행');
})();

```

#### *Example 4.*

```js

function p(ms) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(ms);
        }, ms);
    });
}

// Promise.all

async function main() {
    const results = await Promise.all([p(1000), p(2000), p(3000)]);
    console.log(results);
})();
// [ 1000, 2000, 3000 ] 이 나온다. 

// Promise.race

async function main() {
    const result = await Promise.reac([p(1000), p(2000), p(3000)]);
    console.log(result);
}
// 1000이 나올 것이다.

```
